title: String.toURI() for JavaScript
description: Transliteration for JavaScript & Node.js, basically used for SEO URI generation. As small and simple as possible.
google_analytics: UA-23960333-9
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
